config/routes.rb
Kiseki::Application.routes.draw do
  resources :characters

  root :to => "home#index"

  devise_for :users
  
  resources :users, :only => [:show] do
    member do
      get 'update_photo_url'
    end
  end
  
  match "/welcome" => "users#welcome"

end

app/models/character.rb
class Character < ActiveRecord::Base

  BASE_STAT = 5
  ALL_STATS = ['charisma', 'wit', 'stalkability']

  belongs_to :user

  before_create :generate_character

  def bonus_charisma(social_profiles)
    begin
      #social_profiles = Rainmaker.person(user.email).social_profiles unless social_profiles
      
      twitter = social_profiles.select{ |sp| sp.type.eql?("twitter") }.first
      
      if twitter
        followers_count = Twitter.user(twitter.username).followers_count
        Math.log(followers_count, 2).floor
      else
        0
      end
    rescue
      0
    end
  end
  
  def bonus_wit(social_profiles)
    begin
      #social_profiles = Rainmaker.person(user.email).social_profiles unless social_profiles
      
      twitter = social_profiles.select{ |sp| sp.type.eql?("twitter") }.first
      
      if twitter
        tweets = Twitter.user(twitter.username).statuses_count
        Math.log(tweets, 3).floor
      else
        0
      end
    rescue
      0
    end
  end
  
  def bonus_stalkability(response)
    begin
      #response = Rainmaker.person(user.email) unless response
      
      if response 
        social_profile_count(response) + social_photo_count(response)
      else
        -2
      end
    rescue
      0
    end
  end
  
  def get_photos
    begin
      response = Rainmaker.person(user.email)
      
      photos = response.try(:photos).inject([]) { |photo_array, photo| photo_array << photo unless photo_array.map(&:type).include?(photo.type); photo_array }
    rescue
      []
    end
  end
  
  private
    def generate_character
      rainmaker_response = Rainmaker.person(user.email)
    
      # for every 10 followers in twitter, +1 charisma
      self.charisma            = BASE_STAT + bonus_charisma(rainmaker_response.social_profiles)
    
      # for every status message in fb and twitter?
      self.wit                 = BASE_STAT + bonus_wit(rainmaker_response.social_profiles)
    
      # for every social profile, +1
      self.stalkability        = BASE_STAT + bonus_stalkability(rainmaker_response)
    end
    
    def social_profile_count(response)
      begin
        (response.social_profiles && response.social_profiles.count > 1) ? response.social_profiles.count : -1
      rescue
        0
      end
    end
    
    def social_photo_count(response)
      (response.photos && response.photos.count > 1) ? response.photos.count : -1
    end

end

# == Schema Information
#
# Table name: characters
#
#  id           :integer         not null, primary key
#  name         :string(255)
#  type_id      :integer
#  charisma     :integer
#  wit          :integer
#  stalkability :integer
#  created_at   :datetime
#  updated_at   :datetime
#  user_id      :integer
#

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  has_one :character, :dependent => :destroy
         
  # validates_presence_of :login
  validates_uniqueness_of :email, :case_sensitive => false

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  
  after_create :generate_character
  
  private
    def generate_character
      self.create_character(:name => "#{email}'s avatar")
    end
  
end
# == Schema Information
#
# Table name: users
#
#  id                     :integer         not null, primary key
#  email                  :string(255)     default(""), not null
#  encrypted_password     :string(128)     default(""), not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer         default(0)
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string(255)
#  last_sign_in_ip        :string(255)
#  created_at             :datetime
#  updated_at             :datetime
#

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_filter :authenticate_user!, :only => [:welcome]

  def index
    if current_user
      redirect_to welcome_path
    end
  end
  
end

app/controllers/users/users_controller.rb
class User::UsersController < ApplicationController
  before_filter :authenticate_user!

  def show
    @user = User.find(params[:id])
  end
  
  def welcome
    @user = current_user
    @character = current_user.character
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!
    
  def show
    @user = User.find(params[:id])
  end
  
  def welcome
    @character = current_user.character
    
    @photos = @character.get_photos unless @character.photo_url
  end
  
  def update_photo_url
    if current_user.character.update_attributes(:photo_url => params[:photo_url])
      redirect_to root_path
    else
      render "welcome", :error => "There was a problem in saving your preference"
    end
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/characters_helper.rb
module CharactersHelper
  
  def base_value_of(stat)
    Character::BASE_STAT
  end
  
  def bonus_value_of(stat)
    bonus = current_user.character.send(stat.to_sym) - Character::BASE_STAT
    if bonus > 0
      #"<span class='positive'>+#{bonus}</span>"
      "+#{bonus}"
    elsif bonus < 0
      "-#{bonus}"
      #"<span class='negative'>-#{bonus}</span>"
    else
      0
    end
  end
  
  def total_value_of(stat)
    current_user.character.send(stat.to_sym)
    # current_user.character.send(stat.to_sym) + current_user.character.send("bonus_#{stat}".to_sym)
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.haml
%h3 What is Kiseki?

%p
  Right now, Kiseki is a tool to create your very own internet avatar. No, it's not just a picture of you, or a "tinier" you. It is an avatar that represents who you really are - in the internet.
  
%p
  Think of a character in a role playing game or a fantasy novel. Thought of someone already? What if you were that someone, thrust into the internet to save a princess or to vanquish a dragon? You can be that person in Kiseki.
  
%p
  Right now, Kiseki is still nurturing itself and trying to grow. As more avatars emerge in this world, the more the world grows and the more you will see its potential.

%h3 What do I do for now?

%p
  You just need to supply an email address (and password - so you can login!). When you register, you will be creating a character avatar for yourself. Of course, you will be a lowly character at first. But when you enchant it with Kiseki, your character can gain more stats in an instant!
  
%h3 What stats are there?

%p
  Currently there are three stats that describe your character(it will grow to 5-10 in the future. The possibilities are endless in Kiseki!):
  
%ul.stat-list
  %li
    %strong Charisma
    %span
      %em
        = "- This grows based on the number of your followers in"
        = link_to "Twitter", "http://twitter.com"
  %li
    %strong Wit
    %span
      %em 
        = "- This grows based on the number of your tweets"
        (this will be eventually optional to include facebook statuses)
  %li
    %strong Stalkability
    %span
      %em
        = "- based on your internet visibility. The more social profiles you have, the higher this will go"
      %small
        (Keep in mind that lacking certain social profiles actually decreases your stalkability, but don't fret! This doesn't mean it's a bad thing.)
      
%h3 How will you know about these things?
  
%p
  Via the
  = link_to "Rainmaker API", "http://rainmaker.cc/"
  
%p
  Basically, it just searches the internet for your public information based on your email. To be clear, you're giving the email(and your data, since it is public) freely and Rainmaker just compiles and generates a character based on those data.
      
%h3 Still interested?

%p
  Hop in and 
  %strong= link_to "sign up now", new_user_registration_path
  to receive updates and get your bonus starting points!

app/views/layouts/_flashes.html.haml
#flash
  - flash.each do |key, value|
    .message{ :class => key }
      %p= value

app/views/layouts/_footer.html.haml
%small.copyright
  deadcanvas &copy; #{Date.today.year}

app/views/layouts/_head.html.haml
%meta{ :charset => "utf-8" }/

-# Always force latest IE rendering engine (even in intranet) & Chrome Frame
-# Remove this if you use the .htaccess
%meta{ "http-equiv" => "X-UA-Compatible", :content => "IE=edge,chrome=1" }/

%title= "#{ controller.controller_name.titleize } - #{ controller.action_name.titleize }"

= render "stylesheets"

-# Mobile viewport optimized: j.mp/bplateviewport
%meta{ :name => "viewport", :content => "width=device-width, initial-scale=1.0" }/

= csrf_meta_tag

app/views/layouts/_header.html.haml
%h1 Kiseki

%h5 Create your own internet avatar

app/views/layouts/_javascripts.html.haml
= javascript_include_tag "jquery", "users"

app/views/layouts/_nav.html.haml
%ul.menu
  = render 'devise/menu/registration_items'
  = render 'devise/menu/login_items'

app/views/layouts/_stylesheets.html.haml
= stylesheet_link_tag 'http://fonts.googleapis.com/css?family=Artifika'
= stylesheet_link_tag 'application', :media => 'all'
= stylesheet_link_tag 'main', :media => 'all'

-# Append your own using content_for :stylesheets
= yield :stylesheets

app/views/layouts/application.html.haml
!!! 5
%head
  = render "layouts/head"

%body{ :class => "#{controller.controller_name}" }
  #container
    %header#header
      = render "layouts/header"
      = render "layouts/nav"
      
    #main{ :role => 'main' }
      = render "layouts/flashes"
      = yield
      
    %footer#footer
      = render "layouts/footer"
      
    = render "layouts/javascripts"

app/views/users/_photos.html.haml
.character-photos
  - unless current_user.character.photo_url
    - unless photos.empty?
    
      %h5 Choose your favorite avatar
    
      %ul
        / %li
        /   %a
        /     = image_tag("http://www.google.com/s2/photos/public/AIbEiAIAAABECP3Rr-GMg57twQEiC3ZjYXJkX3Bob3RvKig4MTBlOGNjYTZhNmY4MjY5MGMxNTQwMTA3NGRlMDUyMjYyNmFhMTY4MAH7gGw4tTM130V7InSH8WYsyHHDog", :class => "avatar")
        /     %small google profile
        / %li
        /   %a
        /     = image_tag("http://profile.ak.fbcdn.net/hprofile-ak-snc4/186042_842342271_8264627_q.jpg", :class => "avatar")
        /     %small facebook
        - photos.each do |photo|
          %li
            %a{:href => "#{update_photo_url_user_path(current_user)}?photo_url=#{photo.url}", :class => "update-photo"}
              = image_tag(photo.url, :class => "avatar")
              %small
                = photo.type
                
  - else
    %p
      = image_tag(current_user.character.photo_url, :class => "avatar")

app/views/users/show.html.haml
%p 
  User: 
  = @user.email

app/views/users/welcome.html.haml
%h3 Welcome!

%p
  Below are your character stats. As you update more of your social profiles, you will gain more stats and your character will grow stronger. Check back once in awhile to see how your character is doing. Soon, Kiseki will be ready to launch and your avatar will be put to the test!

#character-info  
  %table.character-stats
    %tr
      %th &nbsp;
      %th.base.value Base
      %th.bonus.value Bonus
      %th.total.value Total
  
    - Character::ALL_STATS.each do |stat|
      %tr
        %td= stat.titleize
        %td.base.value= base_value_of(stat)
        %td.bonus.value= bonus_value_of(stat)
        %td.bonus.value= total_value_of(stat)

  = render :partial => "photos", :locals => {:photos => @photos}
        